---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Create mount directory
      ansible.builtin.file:
        path: /mnt/www
        state: directory
        mode: 0750
