---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    provider_raw_config_args:
      - "customize
         ['createhd',
          '--filename', 'extradisk_centos_7.vdi',
          '--size', 1024]"
      - "customize
         ['storageattach', :id,
          '--storagectl', 'IDE',
          '--port', 1,
          '--device', 1,
          '--type', 'hdd',
          '--medium', 'extradisk_centos_7.vdi']"
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    box: centos/stream8
    provider_raw_config_args:
      - "customize
         ['createhd',
          '--filename', 'extradisk_centos_8.vdi',
          '--size', 1024]"
      - "customize
         ['storageattach', :id,
          '--storagectl', 'IDE',
          '--port', 1,
          '--device', 1,
          '--type', 'hdd',
          '--medium', 'extradisk_centos_8.vdi']"
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora34-${INSTANCE_UUID:-1}"
    box: fedora/34-cloud-base
    provider_raw_config_args:
      - "customize
         ['createhd',
          '--filename', 'extradisk_centos_8.vdi',
          '--size', 1024]"
      - "customize
         ['storageattach', :id,
          '--storagectl', 'IDE',
          '--port', 1,
          '--device', 1,
          '--type', 'hdd',
          '--medium', 'extradisk_centos_8.vdi']"
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_fedora_34
  - name: "fedora35-${INSTANCE_UUID:-1}"
    box: fedora/35-cloud-base
    provider_raw_config_args:
      - "customize
         ['createhd',
          '--filename', 'extradisk_centos_8.vdi',
          '--size', 1024]"
      - "customize
         ['storageattach', :id,
          '--storagectl', 'IDE',
          '--port', 1,
          '--device', 1,
          '--type', 'hdd',
          '--medium', 'extradisk_centos_8.vdi']"
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_fedora_35
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          migrate_to_mount:
            - mount:
                path: /var/www
                src: /dev/mapper/vgtesting-lvtest
                opts: 'context="system_u:object_r:httpd_sys_content_t:s0"'
                owner: apache
                group: apache
                mode: "0755"
                fstype: xfs
              service:
                name: httpd
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
